---
#######################################
# Setup Tasks
#######################################
- name: "SETUP: fetch LVM facts"
  lvm_facts:
    name: all
    component: all
  register: facts
- debug: var=facts

- name: "SETUP: create volume group"
  lvg:
    state: present
    vg_name: "{{ vg_name }}"
    pvs: "{{ pv_list }}"
    force: "{{ force }}"
  register: lvg_results
  when:
  - facts.ansible_facts.LVM.VGs.{{ vg_name }} is not defined

- name: "SETUP: create a logical volume"
  lvol:
    state: present
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    lv_type: "{{ lv_type }}"
    size: "{{ lv_size }}"
  when:
  - (lvg_results is changed) or
    (facts.ansible_facts.LVM.LVs.{{ lv_name }} is not defined)

#######################################
# Actual Task To Be Tested
#######################################
- name: "TC07_S01: rename logical volume"
  lvol:
    state: present
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    lv_type: "{{ lv_type }}"
    size: "{{ lv_size_new }}"
    lv_new_name: "{{ lv_name_new }}"
  register: results
  # expect error on second run as lv has a diffirent name
  ignore_errors: true
- debug: var=results

- name: "TC07_S01_ASSERT1: expected results - first run"
  assert:
    that:
    - results.msg.find( "renamed into" ) != -1
    - results.cmd.find( "chlv -n" ) != -1
  when:
  - results is changed
  - facts.ansible_facts.LVM.LVs.{{ lv_name_new }} is not defined

- name: "TC07_S01_ASSERT2: expected results - second run"
  assert:
    that:
    - results.msg.find( "Failed to rename" ) != -1
  when:
  - results is failed
  - facts.ansible_facts.LVM.LVs.{{ lv_name_new }} is defined
